# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class BaseUiFeishuDoc(object):

    def setupUi(self, feishu_doc):
        feishu_doc.setObjectName("feishu_doc")
        feishu_doc.resize(500, 300)
        self.lineEdit = QtWidgets.QLineEdit(feishu_doc)
        self.lineEdit.setGeometry(QtCore.QRect(20, 10, 450, 40))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.listWidget = QtWidgets.QListWidget(feishu_doc)
        self.listWidget.setGeometry(QtCore.QRect(20, 60, 450, 211))
        self.listWidget.setObjectName("listWidget")

        feishu_doc.setWindowTitle("飞书文档搜索")
        feishu_doc.setFixedWidth(490)
        feishu_doc.setFixedHeight(300)
        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(feishu_doc)

    def retranslateUi(self):
        self.lineEdit.setStyleSheet("QLineEdit { border-radius: 4px }")
        self.listWidget.hide()
